version: '3.3'

services:
  # Postgres
  calorie_tracker_db:
    image: postgres

    environment:
      - POSTGRES_USER=luke
      - POSTGRES_PASSWORD=calorie_tracker123
      - POSTGRES_DB=calorie_tracker

  calorie_tracker_web:
    build: .
    command: ["./run_web.sh"]
    volumes:
      - .:/calorie_tracker_project
    ports:
      - "8000:8000"
    links:
      - calorie_tracker_db
    depends_on:
      - calorie_tracker_db
